//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebSite {
    
    
    public partial class Default {
        
        /// <summary>
        /// My_U_Slide1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MyWebSite.Control.Default.My_U_Slide My_U_Slide1;
        
        /// <summary>
        /// My_U_Top_News1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MyWebSite.Control.Default.My_U_Top_News My_U_Top_News1;
        
        /// <summary>
        /// My_U_Top3_News1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MyWebSite.Control.Default.My_U_Top3_News My_U_Top3_News1;
        
        /// <summary>
        /// My_U_Item_Main1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MyWebSite.Control.Default.My_U_Item_Main_News My_U_Item_Main1;
    }
}
